import Header from '../components/Header'
import Head from 'next/head'
import Image from 'next/image'
import {MagnifyingGlassIcon, MicrophoneIcon} from "@heroicons/react/24/solid"
import Footer from '../components/Footer'
import {useRouter} from "next/router"
import { useRef } from "react"

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  function search(event) {
    event.preventDefault();
    const term = searchInputRef.current.value;
    if(!term.trim()) return
    router.push(`/search?term=${term.trim()}&searchType=`)
  }
  return (
    <div>
      <Head>
        <title>Google v3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <from className="flex flex-col items-center mt-40">
        <Image className='object-cover' src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/250px-Google_2015_logo.svg.png" width={300} height={100} />
        <div className='flex w-full border p-1 max-w-[50%] mt-5 mx-auto border-gray-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full items-center sm:max-w-xl lg:max-w-2xl'>
          <MagnifyingGlassIcon className='h-5 text-gray-500 mr-3' />
          <input ref={searchInputRef} type="text" className='flex-grow focus-visible:outline-none' />
          <MicrophoneIcon className='h-5' />
        </div>
        <div className='flex flex-col mt-8 sm:flex-row w-[50%] space-y-2 sm:space-y-0 sm:space-x-4 justify-center'>
          <button onClick={search} className='btn'>Google Search</button>
          <button className='btn'>I'm Feeling Lucky</button>
        </div>
      </from>

      <Footer />
      
    </div>
  )
}
